### ISSUE TITLE
Uncaught Exception: Error read ECONNRESET on finish

### ISSUE THREAD

**Issue by MaxiDoet** [bitfocus/esp-ota#3]
Uploading works but when it finishes i get an exception. I also tried try...catch

![image](https://user-images.githubusercontent.com/38401902/144723467-780be19d-5e5d-459f-9146-5c7df679bcc1.png)

https://jsfiddle.net/z6x183yh/

**Comment by haakonnessjoen** [comment]
Hi, I've pushed a fix to github. Could you please try `npm install github:bitfocus/esp-ota` and try that version, and make sure you handle errors via `esp.on('error', (e) => {});` which would handle asynchronous socket errors.

If it works fine, I will push a new version to npm asap :)

**Comment by MaxiDoet** [comment]
No it still doesn't catch the error. But after some time i got it to work (its not the best way).

`process.on('uncaughtException', (err) => console.log(err));`
